### ISSUE TITLE
Create blog/indexable content for updates about the project.

### ISSUE THREAD

**Issue by jsumnersmith** [birdsumner/dcrc#6]

**Comment by jsumnersmith** [comment]
Just a fair warning. This specific piece is going to take me a bit more time.

**Comment by jsumnersmith** [comment]
I pushed back the milestone involved with this one because time has been tight here. I'll try to knock something out this weekend with a launch date of Sunday.

**Comment by brycehewlett** [comment]
Sunday is fine for the blog. They're really dogging me to get the PayPal button up so we can start receiving donations online. I don't know how much time that would take, but can you get that up in the next day or two? That way the committee can keep moving forward with publicizing the project and receiving donations.

**Comment by jsumnersmith** [comment]
@brycehewlett I got this all squared away. You can now add posts in the backend and simply add the category 'cemetery' which is available in the right hand column when making a post. Any posts with in the 'cemetery' category will show up at the bottom of the project's page.
