### ISSUE TITLE
Add PayPal Button

### ISSUE THREAD

**Issue by brycehewlett** [birdsumner/dcrc#7]
I don't know how hard this would be...

The login info for the PayPal account is as follows.
[deleted the login information]

The button to use is obvious. It's called "Dignity Project Spiral Cemetery."

**Comment by jsumnersmith** [comment]
Sure! Do you have any idea of where you'd like this to be placed?

**Comment by brycehewlett** [comment]
I guess centered in the bottom right above the countdown would be good. Would that work?

**Comment by jsumnersmith** [comment]
Sounds great. I'll get this up by the end of the day.

**Comment by brycehewlett** [comment]
Great!

**Comment by jsumnersmith** [comment]
Sorry that I totally dropped the ball on this on Thursday. It's up and ready now: http://delawarerecovery.org/advocacy/spiralcemetery

**Comment by brycehewlett** [comment]
Looks great! Thanks, Joel!
